const fields = {
  spineTextarea: document.querySelector(".spineTextarea"),
  emitterTextarea: document.querySelector(".emitterTextarea"),
  imageTextarea: document.querySelector(".imageTextarea"),
  framerate: document.querySelector("#framerate"),
  openSidebar: document.querySelector(".openSidebar"),
  closeSidebar: document.querySelector(".closeSidebar"),
  prettyBtn: document.querySelector("#prettyBtn"),
  invalidJson: document.querySelector(".invalidJson"),
  sidebar: document.querySelector("#sidebar"),
  main: document.querySelector("#main"),
  bigwinName: document.querySelector(".bigwinName"),
  bigwinType: document.querySelector(".bigwinType"),
  bigwinDuration: document.querySelector(".bigwinDuration"),
  file: document.querySelector("#file"),
  loader: document.querySelector(".loader"),
  deleteParameter: document.querySelectorAll(".deleteParameter"),
  addParameter: document.querySelector(".addParameter"),

  alphaPopup: document.querySelector(".alphaPopup"),
  speedPopup: document.querySelector(".speedPopup"),
  scalePopup: document.querySelector(".scalePopup"),
  colorPopup: document.querySelector(".colorPopup"),
  speedTable: document.querySelector(".speedTable"),
  scaleTable: document.querySelector(".scaleTable"),
  colorTable: document.querySelector(".colorTable"),
  alphaTable: document.querySelector(".alphaTable"),

  particleControls: document.querySelector(".particleControls"),
  minimumScaleMultiplier: document.querySelector(".minimumScaleMultiplier"),
  minimumSpeedMultiplier: document.querySelector(".minimumSpeedMultiplier"),
  isStepped: document.querySelector(".isStepped"),

  spawnType: document.querySelector(".spawnType"),
  maxParticles: document.querySelector(".maxParticles"),
  emitterLifetime: document.querySelector(".emitterLifetime"),
  frequency: document.querySelector(".frequency"),
  accelerationX: document.querySelector(".accelerationX"),
  accelerationY: document.querySelector(".accelerationY"),
  positionX: document.querySelector(".positionX"),
  positionY: document.querySelector(".positionY"),
  lifetimeMax: document.querySelector(".lifetimeMax"),
  lifetimeMin: document.querySelector(".lifetimeMin"),
  startRotationMin: document.querySelector(".startRotationMin"),
  startRotationMax: document.querySelector(".startRotationMax"),
  rotationSpeedMin: document.querySelector(".rotationSpeedMin"),
  rotationSpeedMax: document.querySelector(".rotationSpeedMax"),
};

export default fields;
